slc: &defaults
  image: loopback
  volumes:
    - .:/app
  working_dir: /app/spike-todo
  links:
    - mongo
  entrypoint: ["slc"]
server:
  <<: *defaults
  entrypoint: ["slc","run"]
  ports:
    - "3000:3000"
npm:
  <<: *defaults
  entrypoint: ["npm"]
mongo:
  image: mongo
  volumes:
    - ./mongo:/data/db